from __future__ import annotations

import tempfile
import unittest
from pathlib import Path

from tests.test_support import add_src_to_path

add_src_to_path()

from dockly.config import sample_dockerfile_config
from dockly.services.dockerfile_service import explain_dockerfile, generate_dockerfile_from_config

FIXTURES = Path(__file__).resolve().parents[1] / "fixtures"


class CapabilityGatingTests(unittest.TestCase):
    def _generate(self, fixture: str, *, use_layered_jar: bool) -> str:
        root = FIXTURES / fixture
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "Dockerfile.generated"
            config = sample_dockerfile_config(
                build_tool=None,
                output=str(out),
                use_layered_jar=use_layered_jar,
                use_jlink=False,
                enable_appcds=False,
                include_embedded_sbom=False,
                pin_digests=False,
            )
            # Resolve build tool from fixture via generate helper path
            from dockly.project_detect import detect_build_tool

            tool = detect_build_tool(root)
            generate_dockerfile_from_config(root, config, tool)
            return out.read_text(encoding="utf-8")

    def test_spring_layered_branch_emits_layertools(self) -> None:
        text = self._generate("maven-only", use_layered_jar=True)
        self.assertIn("extract --layers", text)
        self.assertIn("/layers/", text)

    def test_spring_non_layered_branch_skips_layertools(self) -> None:
        text = self._generate("maven-only", use_layered_jar=False)
        self.assertNotIn("extract --layers", text)
        self.assertNotIn("jarmode=layertools", text)
        # Still a Spring/Java multi-stage Dockerfile
        self.assertIn("FROM", text)
        self.assertIn("Java ", text)

    def test_plain_java_branch_never_uses_layertools(self) -> None:
        text = self._generate("plain-java-maven", use_layered_jar=True)
        self.assertNotIn("extract --layers", text)
        self.assertNotIn("layertools", text)
        self.assertIn("Generated by dockly", text)

    def test_explain_states_capability_path(self) -> None:
        root = FIXTURES / "maven-only"
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "Dockerfile.generated"
            config = sample_dockerfile_config(
                output=str(out),
                use_layered_jar=True,
                use_jlink=False,
                enable_appcds=False,
                include_embedded_sbom=False,
                pin_digests=False,
            )
            from dockly.project_detect import detect_build_tool

            generate_dockerfile_from_config(root, config, detect_build_tool(root))
            # Explain relative to fixture root with dockerfile in temp — copy text into fixture-adjacent path
            df = root / "Dockerfile.explain-test"
            try:
                df.write_text(out.read_text(encoding="utf-8"), encoding="utf-8")
                payload = explain_dockerfile(root, "Dockerfile.explain-test")
            finally:
                if df.exists():
                    df.unlink()
        path_info = payload["capability_path"]
        assert isinstance(path_info, dict)
        self.assertEqual(path_info["path"], "spring-layered")
        self.assertEqual(path_info["strategy_id"], "spring-boot-layered")
        self.assertIn("rationale", path_info)
        self.assertTrue(path_info["dockerfile_has_layered_jar"])

    def test_explain_plain_java_path(self) -> None:
        root = FIXTURES / "plain-java-maven"
        with tempfile.TemporaryDirectory() as td:
            out = Path(td) / "Dockerfile.generated"
            config = sample_dockerfile_config(
                output=str(out),
                use_layered_jar=True,
                use_jlink=False,
                enable_appcds=False,
                include_embedded_sbom=False,
                pin_digests=False,
            )
            from dockly.project_detect import detect_build_tool

            generate_dockerfile_from_config(root, config, detect_build_tool(root))
            df = root / "Dockerfile.explain-test"
            try:
                df.write_text(out.read_text(encoding="utf-8"), encoding="utf-8")
                payload = explain_dockerfile(root, "Dockerfile.explain-test")
            finally:
                if df.exists():
                    df.unlink()
        path_info = payload["capability_path"]
        assert isinstance(path_info, dict)
        self.assertEqual(path_info["path"], "plain-java")
        self.assertEqual(path_info["strategy_id"], "plain-java")
        self.assertFalse(path_info["dockerfile_has_layered_jar"])


if __name__ == "__main__":
    unittest.main()
